#!/usr/bin/perl
#

our $target = "create_infini_rrd.sh";
our $step = 5;

our $hb_sec = 10 / $step ;		# 10 s granularity
our $r_sec = 86400;			# 10 days

$hb_min = 300 / $step ;		# 5 min granularity
$r_min = 26000 ;		# 3 monts

$hb_hr = 3600 / $step ;		# 1 hr granularity
$r_hr = 10000;			# > 1 yr

$hb_day = 24 * $hb_hr ;		# 24 hr granularity
$r_day = 22000;			# 6 yrs



# import('./P17_def.pm6');
# use P17_def ;
# our %p17;
our @rrd_def;
require ('./P17_def.pl');

# rehash ??
#

$rrdtool =`which rrdtool`;
chomp $rrdtool ;
our $nl = " \\\n";

my $cmd = <<'HEAD';
#!/bin/bash
# skript to generate rrd files
# generated by
HEAD

$cmd .= "# $0 $nl";
$cmd .= "$rrdtool create infini.rrd --start NOW";
$cmd .= sprintf (" --step %d ", $step );
$cmd .=  $nl;


foreach $field (@rrd_def) {
  my ( $label, $P17cmd, $P17pos, $min, $max) = @$field;
  $cmd .= sprintf ("DS:%s:GAUGE:%d:%d:%d%s", $label, 10, $min, $max, $nl );
}


$cmd .= rra ( $hb_sec, $r_sec, 'AVERAGE');
$cmd .= rra ( $hb_min, $r_min, 'MIN', 'MAX', 'AVERAGE');
$cmd .= rra ( $hb_hr,  $r_hr,  'MIN', 'MAX', 'AVERAGE');
$cmd .= rra ( $hb_day,  $r_day,  'MIN', 'MAX', 'AVERAGE');

print $cmd, "\n\n";


open ( TARGET , '>' ,  $target) or die "$! \n could not open $target";
print TARGET $cmd;
close TARGET;
print "$target written\n";

print ` chmod +x $target`;


exit;
# --------------------------
# rra (steps, rows, list-of-CF-tags)
sub rra {
  my $rv="";
  my $s = shift ;
  my $r = shift ;
  foreach my $tag ( @_ ) {
    $rv .= sprintf ("RRA:%s:0.5:%d:%d %s", $tag , $s, $r , $nl );
  }
  return $rv ;
}


